; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
workspace_dir = d:\tmp\pio\test bno85

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D SERIAL_SPEED=115200
  -D GMT024
  ;-D USE_TEMP_SENSOR
lib_deps = 
  adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
  adafruit/Adafruit GFX Library@^1.11.0  
  milesburton/DallasTemperature @ ^4.0.6

[env:test_BNO085_ADAFRUIT]
build_flags =
  ${env.build_flags}
  -D ADAFRUIT_BNO085
lib_deps = 
  ${env.lib_deps}
  adafruit/Adafruit BNO08x@^1.2.5
  adafruit/Adafruit BusIO@^1.11.0
;*********************************************** 

[env:test_BNO085_SPARKFUN]
build_flags =
  ${env.build_flags}
  -D SPARKFUN_BNO085
lib_deps = 
  ${env.lib_deps}
  sparkfun/SparkFun BNO08x Cortex Based IMU @ ^1.0.6