; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
workspace_dir = d:\tmp\pio\pio_bno085
lib_dir = ../../../lib/lib

; [env:CapteurBNO085]
; platform = espressif32
; board = esp32-c3-devkitm-1 ; Modifie selon ta carte exacte si besoin
; framework = arduino

; monitor_speed = 115200
; monitor_dtr = 0
; monitor_rts = 0

; build_flags = 
;     ;-D ARDUINO_USB_MODE=1
;     ;-D ARDUINO_USB_CDC_ON_BOOT=1
;     -D SERIAL_SPEED=115200
; lib_deps = 
;     adafruit/Adafruit BNO08x @ ^1.2.5

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags = 
	;-D CORE_DEBUG_LEVEL=3
	-D SERIAL_SPEED=115200
	-D FTPPath=\"bno085\"
	-D SID=\"bno085\"
	-D nomDevice=\"bno085\"
	-D DeviceId=\"bno085Id\"
	;-D ReadDeviceConfigInProject
	
	-D GHFS_ACTIF
	-D OTA_ACTIF
	-D ota_password=\"Archiduc\"
	-D ota_port=8266
	-D USE_RGB_LED
	
	-D ASYNCWEBSERVER_REGEX=1
	-D HA_ACTIF
	-D ESPINFOS_ACTIF
	-D LOG_ACTIF
	-D MAX_LOG=2000
	-D LOG_DEBUG
	-D FTP_ACTIF
	-D HORLOGE_ACTIF
	-D CONFIG_ACTIF
	-D SPIFFS_ACTIF
	-D CONFIG_DEBUG
	
	-D ASTRONOMY_ENGINE_WHOLE_SECOND
lib_deps = 
	FASTLED
	bblanchon/ArduinoJson@^7.4.2
	paulstoffregen/Time@^1.6.1
	arduino-libraries/NTPClient @^3.2.1
	ottowinter/ESPAsyncWebServer-esphome @ ^3.4.0
    adafruit/Adafruit BNO08x @ ^1.2.5

[env:CapteurBNO085]

[env:CapteurBNO085_OTA]
upload_protocol = espota
upload_flags = 
	--port=8266
	--auth=Archiduc
upload_port = 192.168.0.229  